# Generated by Django 2.0.1 on 2018-06-14 20:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('assigned_token', models.IntegerField(blank=True, null=True)),
                ('assigned_doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guest_patients_queue', to='api.Doctor')),
            ],
        ),
        migrations.CreateModel(
            name='LabReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bloodGroup', models.CharField(blank=True, max_length=255, null=True)),
                ('RH', models.CharField(blank=True, max_length=255, null=True)),
                ('completeHemogram', models.CharField(blank=True, max_length=255, null=True)),
                ('ESR', models.CharField(blank=True, max_length=255, null=True)),
                ('HB', models.CharField(blank=True, max_length=255, null=True)),
                ('bleedingTime', models.CharField(blank=True, max_length=255, null=True)),
                ('clottingTime', models.CharField(blank=True, max_length=255, null=True)),
                ('bloodSugarFasting', models.CharField(blank=True, max_length=255, null=True)),
                ('bloodSugarPostPrandial', models.CharField(blank=True, max_length=255, null=True)),
                ('bloodSugarRandom', models.CharField(blank=True, max_length=255, null=True)),
                ('uricAcid', models.CharField(blank=True, max_length=255, null=True)),
                ('MP', models.CharField(blank=True, max_length=255, null=True)),
                ('widal', models.CharField(blank=True, max_length=255, null=True)),
                ('sugar', models.CharField(blank=True, max_length=255, null=True)),
                ('albumin', models.CharField(blank=True, max_length=255, null=True)),
                ('bileSalts', models.CharField(blank=True, max_length=255, null=True)),
                ('bilePigments', models.CharField(blank=True, max_length=255, null=True)),
                ('microscopy', models.CharField(blank=True, max_length=255, null=True)),
                ('ova', models.CharField(blank=True, max_length=255, null=True)),
                ('cyst', models.CharField(blank=True, max_length=255, null=True)),
                ('bloodSugarFasting2', models.CharField(blank=True, max_length=255, null=True)),
                ('bloodSugarRandom2', models.CharField(blank=True, max_length=255, null=True)),
                ('bloodSugarPostPrandial2', models.CharField(blank=True, max_length=255, null=True)),
                ('serumUrea', models.CharField(blank=True, max_length=255, null=True)),
                ('serumCreatinine', models.CharField(blank=True, max_length=255, null=True)),
                ('serumCholestrol', models.CharField(blank=True, max_length=255, null=True)),
                ('HDL', models.CharField(blank=True, max_length=255, null=True)),
                ('LDL', models.CharField(blank=True, max_length=255, null=True)),
                ('TC_HDL', models.CharField(blank=True, max_length=255, null=True)),
                ('triglycerides', models.CharField(blank=True, max_length=255, null=True)),
                ('LFTSerumProtein', models.CharField(blank=True, max_length=255, null=True)),
                ('LFTSerumAlbumin', models.CharField(blank=True, max_length=255, null=True)),
                ('LFTSerumGlobulin', models.CharField(blank=True, max_length=255, null=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.SET_NULL, to='api.Doctor')),
            ],
        ),
        migrations.CreateModel(
            name='LoggedUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PatientHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indication', models.CharField(max_length=255)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.SET_NULL, related_name='treatment_history', to='api.Doctor')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'MALE'), ('F', 'FEMALE'), ('O', 'OTHER')], max_length=1)),
                ('phone', models.CharField(max_length=15)),
                ('guardian_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('local_address', models.TextField()),
                ('permanent_address', models.TextField()),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3)),
                ('patient_type', models.CharField(choices=[('S', 'STUDENT'), ('E', 'EMPLOYEE'), ('D', 'DEPENDANT')], max_length=1)),
                ('retired', models.NullBooleanField(default=False)),
                ('designation', models.CharField(blank=True, max_length=255, null=True)),
                ('assigned_token', models.IntegerField(blank=True, null=True)),
                ('assigned_doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients_queue', to='api.Doctor')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Course')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Department')),
                ('patron', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dependants', to='api.Person')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='person', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='patienthistory',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_history', to='api.Person'),
        ),
        migrations.AddField(
            model_name='labreport',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Person'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.Person'),
        ),
    ]
