# Generated by Django 2.0.1 on 2018-03-11 14:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180306_0646'),
    ]

    operations = [
        migrations.CreateModel(
            name='DispensedDrug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('batch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Batch')),
            ],
        ),
        migrations.CreateModel(
            name='PharmaRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PharmaRecordBuffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('S', 'SENT'), ('N', 'UNSENT'), ('A', 'ACKNOWLEDGED')], max_length=1)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.PharmaRecord')),
            ],
        ),
        migrations.AlterField(
            model_name='person',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Course'),
        ),
        migrations.AlterField(
            model_name='person',
            name='guardian_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='person', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Person'),
        ),
        migrations.AddField(
            model_name='pharmarecord',
            name='prescription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Prescription'),
        ),
        migrations.AddField(
            model_name='dispenseddrug',
            name='record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispensed_drugs', to='api.PharmaRecord'),
        ),
        migrations.AlterUniqueTogether(
            name='dispenseddrug',
            unique_together={('batch', 'record')},
        ),
    ]
