# Generated by Django 2.0.1 on 2018-06-11 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180611_1358'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='doctorpatientmap',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='doctorpatientmap',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='doctorpatientmap',
            name='patient',
        ),
        migrations.AddField(
            model_name='person',
            name='assigned_doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients_queue', to='api.Doctor'),
        ),
        migrations.DeleteModel(
            name='DoctorPatientMap',
        ),
    ]
